dist: trusty
sudo: required

language: bash

addons:
  hosts:
    - le1.wtf
    - le2.wtf
    - le3.wtf

env:
  global:
    - IMAGE=jrcs/letsencrypt-nginx-proxy-companion
    - NGINX_CONTAINER_NAME=nginx-proxy
    - DOCKER_GEN_CONTAINER_NAME=nginx-proxy-gen
    - TEST_DOMAINS=le1.wtf,le2.wtf,le3.wtf
  matrix:
    - SETUP=2containers
    - SETUP=3containers

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose.temp
  - chmod +x docker-compose.temp
  - sudo mv docker-compose.temp /usr/local/bin/docker-compose

install:
  - docker build -t "$IMAGE" .
  - docker inspect "$IMAGE"
  - docker run --rm "$IMAGE" simp_le --version
  - docker run --rm "$IMAGE" simp_le -v --test
  - docker images

before_script:
  - git clone https://github.com/docker-library/official-images.git official-images
  - test/setup/setup-boulder.sh
  - test/setup/setup-nginx-proxy.sh
  - docker pull nginx:alpine

script:
  - official-images/test/run.sh "$IMAGE"
  - test/run.sh "$IMAGE"

after_failure:
  - docker logs $NGINX_CONTAINER_NAME
  - docker logs default_cert
  - docker logs certs_single
  - docker logs certs_san
  - docker logs force_renew
  - docker logs permissions_default
  - docker logs permissions_custom
  - docker logs symlinks
  - docker logs boulder
  - if [[ $SETUP = "3containers" ]]; then docker logs $DOCKER_GEN_CONTAINER_NAME; fi
